// angular/src/app/components/service-http/art-item/art-item.ts
import { Component, input } from '@angular/core';
import { Artwork } from '../../../models/artwork.model';

@Component({
  selector: 'app-art-item',
  imports: [],
  templateUrl: './art-item.html',
  styleUrl: './art-item.scss'
})
export class ArtItem {

  inputValue = input<Artwork>();


  getDescription(): string {
    return this.inputValue()?.description || 'No description available.' + ' Origin: ' + (this.inputValue()?.place_of_origin || 'Unknown');
  }

}

// reactv1/src/components/ArtItem.tsx
//import './ArtItem.scss';
import React from 'react';
import type { Artwork } from '../models/artwork.model';


interface ArtItemProps {
  inputValue: Artwork;
}

const ArtItem: React.FC<ArtItemProps> = ({ inputValue }) => {
  const getDescription = (): string => {
    return inputValue?.description || 'No description available.' + ' Origin: ' + (inputValue?.place_of_origin || 'Unknown');
  };

  return (
    <div className="card-container">
      <div className="title">{inputValue?.id + ' - ' + inputValue?.title}</div>
      <div className="description" dangerouslySetInnerHTML={{ __html: getDescription() }}></div>
    </div>
  );
};

export default ArtItem;
